l_spanish:
 com_topbar_configuration_button_tooltip: "Abrir pantalla de Configuración de Barra Superior"
 com_topbar_configuration_title: "Configuración de Barra Superior"
 com_topbar_configuration_current: "Barra Superior Actual"
 com_topbar_configuration_add: "Modificar Barra Superior"
 com_topbar_configuration_always_show: "Simpre enseñar elementos de la barra superior (#r Encima de ventanas#!)"
 com_topbar_configuration_add_explanation: "Agregue o elimine elementos de la barra superior usando los botones a continuación."
 com_topbar_configuration_clear_first_tooltip: "Borrar la primera fila de la barra superior."
 com_topbar_configuration_add_first_tooltip: "Agregar este elemento a la primera fila de la barra superior."
 com_topbar_configuration_remove_first_tooltip: "Restar este elemento de la primera fila de la barra superior."
 com_topbar_configuration_clear_second_tooltip: "Borrar la segunda fila de la barra superior."
 com_topbar_configuration_add_second_tooltip: "Agregar este elemento a la segunda fila de la barra superior."
 com_topbar_configuration_remove_second_tooltip: "Restar este elemento de la segunda fila de la barra superior."
 com_topbar_configuration_add_header_source: "Origen de este elemento"
 com_topbar_configuration_add_header_element: "Elemento de la Barra Superior"
 com_topbar_configuration_add_header_first: "1.a\nFila"
 com_topbar_configuration_add_header_second: "2.a\nFila"