l_turkish:
 com_topbar_configuration_button_tooltip: "Topbar Yapılandırmasını Aç"
 com_topbar_configuration_title: "Topbar Yapılandırması"
 com_topbar_configuration_current: "Mevcut Topbar"
 com_topbar_configuration_add: "Topbar Düzenle"
 com_topbar_configuration_add_explanation: "Aşağıdaki butonları kullanarak topbar elemanlarını ekleyip çıkarabilirsiniz."
 com_topbar_configuration_add_first_tooltip: "Bu öğeyi ilk topbar satırına ekle."
 com_topbar_configuration_remove_first_tooltip: "Bu öğeyi ilk topbar satırından kaldır."
 com_topbar_configuration_add_second_tooltip: "Bu öğeyi ikinci topbar satırına ekle."
 com_topbar_configuration_remove_second_tooltip: "Bu öğeyi ikinci topbar satırından kaldır."
 com_topbar_configuration_clear_second_tooltip: "İkinci topbar satırını temizle."
 com_topbar_configuration_clear_first_tooltip: "Birinci topbar satırını temizle."
 com_topbar_configuration_add_header_source: "Öğe Kaynağı"
 com_topbar_configuration_add_header_element: "Topbar Element"
 com_topbar_configuration_add_header_first: "Birinci\nSatır"
 com_topbar_configuration_add_header_second: "İkinci\nSatır"