l_german:
 com_topbar_configuration_button_tooltip: "Öffnen Sie die Kopfleiste-Konfiguration"
 com_topbar_configuration_title: "Kopfleiste-Konfiguration"
 com_topbar_configuration_current: "Derzeitige Kopfleiste"
 com_topbar_configuration_add: "Kopfleiste bearbeiten"
 com_topbar_configuration_always_show: "Zeigen Sie die Kopfleiste-Elemente immer (#r überlagert Fenster#!)"
 com_topbar_configuration_add_explanation: "Fügen Sie mithilfe der folgenden Schaltflächen Elemente zur Kopfleiste hinzu oder entfernen Sie sie daraus."
 com_topbar_configuration_clear_first_tooltip: "Erste Zeile der Kopfleiste löschen."
 com_topbar_configuration_add_first_tooltip: "Fügen Sie dieses Element zur ersten Zeile der Kopfleiste hinzu."
 com_topbar_configuration_remove_first_tooltip: "Entfernen Sie dieses Element aus der ersten Zeile der Kopfleiste."
 com_topbar_configuration_clear_second_tooltip: "Zweite Zeile der Kopfleiste löschen."
 com_topbar_configuration_add_second_tooltip: "Fügen Sie dieses Element zur zweiten Zeile der Kopfleiste hinzu."
 com_topbar_configuration_remove_second_tooltip: "Entfernen Sie dieses Element aus der zweiten Zeile der Kopfleiste."
 com_topbar_configuration_add_header_source: "Herkunft des Elements"
 com_topbar_configuration_add_header_element: "Kopfleisten-Element"
 com_topbar_configuration_add_header_first: "Erste\nReihe"
 com_topbar_configuration_add_header_second: "Zweite\nReihe"