l_french:
 com_topbar_configuration_button_tooltip: "Ouvrir la configuration de la barre du haut"
 com_topbar_configuration_title: "Configuration de la barre du haut"
 com_topbar_configuration_current: "Barre du haut actuel"
 com_topbar_configuration_add: "Modifier la barre du haut"
 com_topbar_configuration_always_show: "Toujours montrer la barre du haut (#r Fenêtre contextuelle#!)"
 com_topbar_configuration_add_explanation: "Ajouter ou retirer des éléments de la barre du haut en utilisant les bouttons en dessous."
 com_topbar_configuration_clear_first_tooltip: "Vider la première ligne de la barre du haut."
 com_topbar_configuration_add_first_tooltip: "ajouter cet élément à la première ligne de la barre du haut."
 com_topbar_configuration_remove_first_tooltip: "Retirer cet élément à la première ligne de la barre du haut."
 com_topbar_configuration_clear_second_tooltip: "Vider la seconde ligne de la barre du haut."
 com_topbar_configuration_add_second_tooltip: "Ajouter cet élément à la seconde ligne de la barre du haut."
 com_topbar_configuration_remove_second_tooltip: "Retirer cet élément à la seconde ligne de la barre du haut."
 com_topbar_configuration_add_header_source: "Source de l’élément"
 com_topbar_configuration_add_header_element: "Elément dans la barre du haut"
 com_topbar_configuration_add_header_first: "1ère\nLigne"
 com_topbar_configuration_add_header_second: "2ème\nLigne"