l_japanese:
 com_topbar_configuration_button_tooltip: "上部ステータスバー設定を開く"
 com_topbar_configuration_title: "上部ステータスバー設定"
 com_topbar_configuration_current: "現在の表示項目"
 com_topbar_configuration_add: "上部ステータスバーの編集"
 com_topbar_configuration_always_show: "ステータスバーの要素を常に表示（#r ウィンドウの上に重ねて表示#!）"
 com_topbar_configuration_add_explanation: "下のボタンを使用して、上部ステータスバーから表示要素を追加または削除します。"
 com_topbar_configuration_clear_first_tooltip: "1段目の表示項目をすべて削除する。"
 com_topbar_configuration_add_first_tooltip: "この要素を1段目に追加する。"
 com_topbar_configuration_remove_first_tooltip: "この要素を1段目から削除する。"
 com_topbar_configuration_clear_second_tooltip: "2段目の表示項目をすべて削除する。"
 com_topbar_configuration_add_second_tooltip: "この要素を2段目に追加する。"
 com_topbar_configuration_remove_second_tooltip: "この要素を2段目から削除する。"
 com_topbar_configuration_add_header_source: "導入元"
 com_topbar_configuration_add_header_element: "表示要素"
 com_topbar_configuration_add_header_first: "1段目"
 com_topbar_configuration_add_header_second: "2段目"