l_korean:
 com_topbar_configuration_button_tooltip: "상단 표시줄 구성 열기"
 com_topbar_configuration_title: "상단 표시줄 구성"
 com_topbar_configuration_current: "현재 상단 표시줄"
 com_topbar_configuration_add: "상단 표시줄 편집"
 com_topbar_configuration_always_show: "항상 상단 표시줄 요소 표시 (#r 오버레이 창#!)"
 com_topbar_configuration_add_explanation: "아래 버튼을 사용하여 상단 표시줄 요소를 추가하거나 제거하세요."
 com_topbar_configuration_clear_first_tooltip: "첫 번째 상단 막대 행렬을 지웁니다."
 com_topbar_configuration_add_first_tooltip: "이 요소를 첫 번째 상단 표시줄 행렬에 추가합니다."
 com_topbar_configuration_remove_first_tooltip: "이 요소를 첫 번째 상단 표시줄 행렬에서 제거합니다."
 com_topbar_configuration_clear_second_tooltip: "두 번째 상단 막대 행렬을 지웁니다."
 com_topbar_configuration_add_second_tooltip: "이 요소를 두 번째 상단 표시줄 행렬에 추가합니다."
 com_topbar_configuration_remove_second_tooltip: "이 요소를 두 번째 상단 표시줄 행렬에서 제거합니다."
 com_topbar_configuration_add_header_source: "구성 요소 출처"
 com_topbar_configuration_add_header_element: "상단 표시줄 요소"
 com_topbar_configuration_add_header_first: "첫 번째\n행렬"
 com_topbar_configuration_add_header_second: "두 번째\n행렬"