l_korean:
 com_topbar_configuration_button_tooltip: "Open Topbar Configuration"
 com_topbar_configuration_title: "Topbar Configuration"
 com_topbar_configuration_current: "Current Topbar"
 com_topbar_configuration_add: "Edit Topbar"
 com_topbar_configuration_add_explanation: "Add or remove topbar elements from the topbar using the buttons below."
 com_topbar_configuration_add_first_tooltip: "Add this element to first topbar."
 com_topbar_configuration_add_second_tooltip: "Add this element to second topbar."
 com_topbar_configuration_add_header_element: "Topbar Element"
 com_topbar_configuration_add_header_first: "First\nRow"
 com_topbar_configuration_add_header_second: "Second\nRow"